server:
  port: 6659

spring:
  application:
    name: nacos-hemaindex
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true  #取消控制台懒加载，默认false要刷新请求才会在面板显示

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true